#Wap to input eight no. from the user and display all the unique numbers(0nce)

s = set()
n1 = int(input("enter n1:"))
s.add(n1)
n2 = int(input("enter n2:"))
s.add(n2)
n3 = int(input("enter n3:"))
s.add(n3)
n4 = int(input("enter n4:"))
s.add(n4)
n5= int(input("enter n5:"))
s.add(n5)
n6 = int(input("enter n6:"))
s.add(n6)
n7 = int(input("enter n7:"))
s.add(n7)
n8 = int(input("enter n8:"))
s.add(n8)
print(s)